// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using SwaggerDemoClient.Models;

namespace SwaggerDemoClient.Models
{
    public partial class ApplyClause
    {
        private IList<TransformationNode> _transformations;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<TransformationNode> Transformations
        {
            get { return this._transformations; }
            set { this._transformations = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ApplyClause class.
        /// </summary>
        public ApplyClause()
        {
            this.Transformations = new LazyList<TransformationNode>();
        }
    }
}
