// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using SwaggerDemoClient.Models;

namespace SwaggerDemoClient.Models
{
    public partial class ApplyQueryOption
    {
        private ApplyClause _applyClause;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public ApplyClause ApplyClause
        {
            get { return this._applyClause; }
            set { this._applyClause = value; }
        }
        
        private ODataQueryContext _context;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public ODataQueryContext Context
        {
            get { return this._context; }
            set { this._context = value; }
        }
        
        private string _rawValue;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string RawValue
        {
            get { return this._rawValue; }
            set { this._rawValue = value; }
        }
        
        private string _resultClrType;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ResultClrType
        {
            get { return this._resultClrType; }
            set { this._resultClrType = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ApplyQueryOption class.
        /// </summary>
        public ApplyQueryOption()
        {
        }
    }
}
