// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using SwaggerDemoClient.Models;

namespace SwaggerDemoClient.Models
{
    public partial class EdmReferentialConstraintPropertyPair
    {
        private IEdmStructuralProperty _dependentProperty;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IEdmStructuralProperty DependentProperty
        {
            get { return this._dependentProperty; }
            set { this._dependentProperty = value; }
        }
        
        private IEdmStructuralProperty _principalProperty;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IEdmStructuralProperty PrincipalProperty
        {
            get { return this._principalProperty; }
            set { this._principalProperty = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the
        /// EdmReferentialConstraintPropertyPair class.
        /// </summary>
        public EdmReferentialConstraintPropertyPair()
        {
        }
    }
}
