// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using SwaggerDemoClient.Models;

namespace SwaggerDemoClient.Models
{
    public partial class FilterQueryOption
    {
        private ODataQueryContext _context;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public ODataQueryContext Context
        {
            get { return this._context; }
            set { this._context = value; }
        }
        
        private FilterClause _filterClause;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public FilterClause FilterClause
        {
            get { return this._filterClause; }
            set { this._filterClause = value; }
        }
        
        private string _rawValue;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string RawValue
        {
            get { return this._rawValue; }
            set { this._rawValue = value; }
        }
        
        private string _validator;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Validator
        {
            get { return this._validator; }
            set { this._validator = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the FilterQueryOption class.
        /// </summary>
        public FilterQueryOption()
        {
        }
    }
}
