// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using SwaggerDemoClient.Models;

namespace SwaggerDemoClient.Models
{
    public partial class FilterClause
    {
        private SingleValueNode _expression;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public SingleValueNode Expression
        {
            get { return this._expression; }
            set { this._expression = value; }
        }
        
        private IEdmTypeReference _itemType;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IEdmTypeReference ItemType
        {
            get { return this._itemType; }
            set { this._itemType = value; }
        }
        
        private RangeVariable _rangeVariable;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public RangeVariable RangeVariable
        {
            get { return this._rangeVariable; }
            set { this._rangeVariable = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the FilterClause class.
        /// </summary>
        public FilterClause()
        {
        }
    }
}
