// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using SwaggerDemoClient.Models;

namespace SwaggerDemoClient.Models
{
    public static partial class FlightCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Flight> DeserializeJson(JToken inputObject)
        {
            IList<Flight> deserializedObject = new List<Flight>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Flight flight = new Flight();
                flight.DeserializeJson(iListValue);
                deserializedObject.Add(flight);
            }
            return deserializedObject;
        }
    }
}
