// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;

namespace SwaggerDemoClient.Models
{
    public partial class IEdmType
    {
        private int? _typeKind;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? TypeKind
        {
            get { return this._typeKind; }
            set { this._typeKind = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the IEdmType class.
        /// </summary>
        public IEdmType()
        {
        }
    }
}
