// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using SwaggerDemoClient.Models;

namespace SwaggerDemoClient.Models
{
    public partial class IEdmVocabularyAnnotation
    {
        private string _qualifier;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Qualifier
        {
            get { return this._qualifier; }
            set { this._qualifier = value; }
        }
        
        private string _target;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Target
        {
            get { return this._target; }
            set { this._target = value; }
        }
        
        private IEdmTerm _term;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IEdmTerm Term
        {
            get { return this._term; }
            set { this._term = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the IEdmVocabularyAnnotation class.
        /// </summary>
        public IEdmVocabularyAnnotation()
        {
        }
    }
}
