// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using SwaggerDemoClient.Models;

namespace SwaggerDemoClient.Models
{
    public partial class IEdmModel
    {
        private IList<string> _declaredNamespaces;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<string> DeclaredNamespaces
        {
            get { return this._declaredNamespaces; }
            set { this._declaredNamespaces = value; }
        }
        
        private string _directValueAnnotationsManager;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string DirectValueAnnotationsManager
        {
            get { return this._directValueAnnotationsManager; }
            set { this._directValueAnnotationsManager = value; }
        }
        
        private IEdmEntityContainer _entityContainer;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IEdmEntityContainer EntityContainer
        {
            get { return this._entityContainer; }
            set { this._entityContainer = value; }
        }
        
        private IList<IEdmModel> _referencedModels;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<IEdmModel> ReferencedModels
        {
            get { return this._referencedModels; }
            set { this._referencedModels = value; }
        }
        
        private IList<IEdmSchemaElement> _schemaElements;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<IEdmSchemaElement> SchemaElements
        {
            get { return this._schemaElements; }
            set { this._schemaElements = value; }
        }
        
        private IList<IEdmVocabularyAnnotation> _vocabularyAnnotations;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<IEdmVocabularyAnnotation> VocabularyAnnotations
        {
            get { return this._vocabularyAnnotations; }
            set { this._vocabularyAnnotations = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the IEdmModel class.
        /// </summary>
        public IEdmModel()
        {
            this.DeclaredNamespaces = new LazyList<string>();
            this.ReferencedModels = new LazyList<IEdmModel>();
            this.SchemaElements = new LazyList<IEdmSchemaElement>();
            this.VocabularyAnnotations = new LazyList<IEdmVocabularyAnnotation>();
        }
    }
}
