// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using SwaggerDemoClient.Models;

namespace SwaggerDemoClient.Models
{
    public partial class IEdmTypeReference
    {
        private IEdmType _definition;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IEdmType Definition
        {
            get { return this._definition; }
            set { this._definition = value; }
        }
        
        private bool? _isNullable;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public bool? IsNullable
        {
            get { return this._isNullable; }
            set { this._isNullable = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the IEdmTypeReference class.
        /// </summary>
        public IEdmTypeReference()
        {
        }
    }
}
