// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using SwaggerDemoClient.Models;

namespace SwaggerDemoClient.Models
{
    public partial class IEdmEntityContainer
    {
        private IList<IEdmEntityContainerElement> _elements;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<IEdmEntityContainerElement> Elements
        {
            get { return this._elements; }
            set { this._elements = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private string _namespaceVariable;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Namespace
        {
            get { return this._namespaceVariable; }
            set { this._namespaceVariable = value; }
        }
        
        private int? _schemaElementKind;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? SchemaElementKind
        {
            get { return this._schemaElementKind; }
            set { this._schemaElementKind = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the IEdmEntityContainer class.
        /// </summary>
        public IEdmEntityContainer()
        {
            this.Elements = new LazyList<IEdmEntityContainerElement>();
        }
    }
}
