// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using SwaggerDemoClient.Models;

namespace SwaggerDemoClient.Models
{
    public partial class IEdmReferentialConstraint
    {
        private IList<EdmReferentialConstraintPropertyPair> _propertyPairs;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<EdmReferentialConstraintPropertyPair> PropertyPairs
        {
            get { return this._propertyPairs; }
            set { this._propertyPairs = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the IEdmReferentialConstraint class.
        /// </summary>
        public IEdmReferentialConstraint()
        {
            this.PropertyPairs = new LazyList<EdmReferentialConstraintPropertyPair>();
        }
    }
}
