// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;

namespace SwaggerDemoClient.Models
{
    public partial class IEdmPathExpression
    {
        private int? _expressionKind;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? ExpressionKind
        {
            get { return this._expressionKind; }
            set { this._expressionKind = value; }
        }
        
        private IList<string> _path;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<string> Path
        {
            get { return this._path; }
            set { this._path = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the IEdmPathExpression class.
        /// </summary>
        public IEdmPathExpression()
        {
            this.Path = new LazyList<string>();
        }
    }
}
