// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using SwaggerDemoClient.Models;

namespace SwaggerDemoClient.Models
{
    public partial class IEdmEntityContainerElement
    {
        private IEdmEntityContainer _container;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IEdmEntityContainer Container
        {
            get { return this._container; }
            set { this._container = value; }
        }
        
        private int? _containerElementKind;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? ContainerElementKind
        {
            get { return this._containerElementKind; }
            set { this._containerElementKind = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the IEdmEntityContainerElement class.
        /// </summary>
        public IEdmEntityContainerElement()
        {
        }
    }
}
