// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using SwaggerDemoClient.Models;

namespace SwaggerDemoClient.Models
{
    public partial class ODataPath
    {
        private IEdmType _edmType;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IEdmType EdmType
        {
            get { return this._edmType; }
            set { this._edmType = value; }
        }
        
        private IEdmNavigationSource _navigationSource;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IEdmNavigationSource NavigationSource
        {
            get { return this._navigationSource; }
            set { this._navigationSource = value; }
        }
        
        private string _pathTemplate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PathTemplate
        {
            get { return this._pathTemplate; }
            set { this._pathTemplate = value; }
        }
        
        private IList<ODataPathSegment> _segments;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<ODataPathSegment> Segments
        {
            get { return this._segments; }
            set { this._segments = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ODataPath class.
        /// </summary>
        public ODataPath()
        {
            this.Segments = new LazyList<ODataPathSegment>();
        }
    }
}
