// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using SwaggerDemoClient.Models;

namespace SwaggerDemoClient.Models
{
    public partial class ODataQueryContext
    {
        private string _elementClrType;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ElementClrType
        {
            get { return this._elementClrType; }
            set { this._elementClrType = value; }
        }
        
        private IEdmType _elementType;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IEdmType ElementType
        {
            get { return this._elementType; }
            set { this._elementType = value; }
        }
        
        private IEdmModel _model;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IEdmModel Model
        {
            get { return this._model; }
            set { this._model = value; }
        }
        
        private IEdmNavigationSource _navigationSource;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IEdmNavigationSource NavigationSource
        {
            get { return this._navigationSource; }
            set { this._navigationSource = value; }
        }
        
        private ODataPath _path;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public ODataPath Path
        {
            get { return this._path; }
            set { this._path = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ODataQueryContext class.
        /// </summary>
        public ODataQueryContext()
        {
        }
    }
}
