// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using SwaggerDemoClient.Models;

namespace SwaggerDemoClient.Models
{
    public partial class ODataQueryOptions
    {
        private ApplyQueryOption _apply;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public ApplyQueryOption Apply
        {
            get { return this._apply; }
            set { this._apply = value; }
        }
        
        private ODataQueryContext _context;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public ODataQueryContext Context
        {
            get { return this._context; }
            set { this._context = value; }
        }
        
        private CountQueryOption _count;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public CountQueryOption Count
        {
            get { return this._count; }
            set { this._count = value; }
        }
        
        private FilterQueryOption _filter;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public FilterQueryOption Filter
        {
            get { return this._filter; }
            set { this._filter = value; }
        }
        
        private string _ifMatch;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string IfMatch
        {
            get { return this._ifMatch; }
            set { this._ifMatch = value; }
        }
        
        private string _ifNoneMatch;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string IfNoneMatch
        {
            get { return this._ifNoneMatch; }
            set { this._ifNoneMatch = value; }
        }
        
        private OrderByQueryOption _orderBy;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public OrderByQueryOption OrderBy
        {
            get { return this._orderBy; }
            set { this._orderBy = value; }
        }
        
        private ODataRawQueryOptions _rawValues;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public ODataRawQueryOptions RawValues
        {
            get { return this._rawValues; }
            set { this._rawValues = value; }
        }
        
        private string _request;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Request
        {
            get { return this._request; }
            set { this._request = value; }
        }
        
        private SelectExpandQueryOption _selectExpand;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public SelectExpandQueryOption SelectExpand
        {
            get { return this._selectExpand; }
            set { this._selectExpand = value; }
        }
        
        private SkipQueryOption _skip;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public SkipQueryOption Skip
        {
            get { return this._skip; }
            set { this._skip = value; }
        }
        
        private TopQueryOption _top;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public TopQueryOption Top
        {
            get { return this._top; }
            set { this._top = value; }
        }
        
        private string _validator;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Validator
        {
            get { return this._validator; }
            set { this._validator = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ODataQueryOptions class.
        /// </summary>
        public ODataQueryOptions()
        {
        }
    }
}
