// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;

namespace SwaggerDemoClient.Models
{
    public partial class ODataPathSegment
    {
        private string _segmentKind;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string SegmentKind
        {
            get { return this._segmentKind; }
            set { this._segmentKind = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ODataPathSegment class.
        /// </summary>
        public ODataPathSegment()
        {
        }
    }
}
