// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;

namespace SwaggerDemoClient.Models
{
    public partial class OrderByNode
    {
        private int? _direction;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Direction
        {
            get { return this._direction; }
            set { this._direction = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the OrderByNode class.
        /// </summary>
        public OrderByNode()
        {
        }
    }
}
