// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Rest;
using SwaggerDemoClient.Models;

namespace SwaggerDemoClient.Models
{
    public partial class OrderByQueryOption
    {
        private ODataQueryContext _context;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public ODataQueryContext Context
        {
            get { return this._context; }
            set { this._context = value; }
        }
        
        private OrderByClause _orderByClause;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public OrderByClause OrderByClause
        {
            get { return this._orderByClause; }
            set { this._orderByClause = value; }
        }
        
        private IList<OrderByNode> _orderByNodes;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<OrderByNode> OrderByNodes
        {
            get { return this._orderByNodes; }
            set { this._orderByNodes = value; }
        }
        
        private string _rawValue;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string RawValue
        {
            get { return this._rawValue; }
            set { this._rawValue = value; }
        }
        
        private string _validator;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Validator
        {
            get { return this._validator; }
            set { this._validator = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the OrderByQueryOption class.
        /// </summary>
        public OrderByQueryOption()
        {
            this.OrderByNodes = new LazyList<OrderByNode>();
        }
    }
}
