// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using SwaggerDemoClient.Models;

namespace SwaggerDemoClient.Models
{
    public partial class RangeVariable
    {
        private int? _kind;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Kind
        {
            get { return this._kind; }
            set { this._kind = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private IEdmTypeReference _typeReference;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IEdmTypeReference TypeReference
        {
            get { return this._typeReference; }
            set { this._typeReference = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the RangeVariable class.
        /// </summary>
        public RangeVariable()
        {
        }
    }
}
