// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using SwaggerDemoClient.Models;

namespace SwaggerDemoClient.Models
{
    public partial class SelectExpandQueryOption
    {
        private ODataQueryContext _context;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public ODataQueryContext Context
        {
            get { return this._context; }
            set { this._context = value; }
        }
        
        private int? _levelsMaxLiteralExpansionDepth;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? LevelsMaxLiteralExpansionDepth
        {
            get { return this._levelsMaxLiteralExpansionDepth; }
            set { this._levelsMaxLiteralExpansionDepth = value; }
        }
        
        private string _rawExpand;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string RawExpand
        {
            get { return this._rawExpand; }
            set { this._rawExpand = value; }
        }
        
        private string _rawSelect;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string RawSelect
        {
            get { return this._rawSelect; }
            set { this._rawSelect = value; }
        }
        
        private SelectExpandClause _selectExpandClause;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public SelectExpandClause SelectExpandClause
        {
            get { return this._selectExpandClause; }
            set { this._selectExpandClause = value; }
        }
        
        private string _validator;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Validator
        {
            get { return this._validator; }
            set { this._validator = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the SelectExpandQueryOption class.
        /// </summary>
        public SelectExpandQueryOption()
        {
        }
    }
}
