// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using SwaggerDemoClient.Models;

namespace SwaggerDemoClient.Models
{
    public partial class TopQueryOption
    {
        private ODataQueryContext _context;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public ODataQueryContext Context
        {
            get { return this._context; }
            set { this._context = value; }
        }
        
        private string _rawValue;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string RawValue
        {
            get { return this._rawValue; }
            set { this._rawValue = value; }
        }
        
        private string _validator;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Validator
        {
            get { return this._validator; }
            set { this._validator = value; }
        }
        
        private int? _value;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Value
        {
            get { return this._value; }
            set { this._value = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the TopQueryOption class.
        /// </summary>
        public TopQueryOption()
        {
        }
    }
}
