// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;

namespace SwaggerDemoClient.Models
{
    public partial class TransformationNode
    {
        private int? _kind;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Kind
        {
            get { return this._kind; }
            set { this._kind = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the TransformationNode class.
        /// </summary>
        public TransformationNode()
        {
        }
    }
}
